// src/lib/data.ts

export type Student = {
  id: string;
  name: string;
  interest: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  availability: "Weekdays" | "Weekends";
  subject: string;
  role: string;
  trait: string;
};

export const students: Student[] = [
  {
    id: "1",
    name: "Aarav Patel",
    interest: "Interested in Data Structures",
    level: "Beginner",
    availability: "Weekends",
    subject: "Computer Science",
    role: "College student",
    trait: "High engagement",
  },
  {
    id: "2",
    name: "Riya Sharma",
    interest: "Machine Learning & AI",
    level: "Intermediate",
    availability: "Weekdays",
    subject: "Computer Science",
    role: "Final year",
    trait: "Consistent learner",
  },
  {
    id: "3",
    name: "Mohit Verma",
    interest: "Operating Systems",
    level: "Advanced",
    availability: "Weekends",
    subject: "Computer Science",
    role: "Working professional",
    trait: "Focused",
  },
  {
    id: "4",
    name: "Snehal Joshi",
    interest: "Linear Algebra",
    level: "Beginner",
    availability: "Weekdays",
    subject: "Mathematics",
    role: "First year",
    trait: "Curious learner",
  },
  {
    id: "5",
    name: "Karan Malhotra",
    interest: "Full-Stack Web Development",
    level: "Intermediate",
    availability: "Weekends",
    subject: "Computer Science",
    role: "Startup intern",
    trait: "Project focused",
  },
  {
    id: "6",
    name: "Anushka Rao",
    interest: "Probability & Statistics",
    level: "Beginner",
    availability: "Weekdays",
    subject: "Mathematics",
    role: "Second year",
    trait: "Concept driven",
  },
  {
    id: "7",
    name: "Rahul Sengupta",
    interest: "System Design",
    level: "Advanced",
    availability: "Weekends",
    subject: "Computer Science",
    role: "SDE-1",
    trait: "Career switch",
  },
  {
    id: "8",
    name: "Ishita Kapoor",
    interest: "Organic Chemistry",
    level: "Intermediate",
    availability: "Weekdays",
    subject: "Science",
    role: "NEET aspirant",
    trait: "Consistent",
  },
  {
    id: "9",
    name: "Aditya Kulkarni",
    interest: "Network Security",
    level: "Advanced",
    availability: "Weekends",
    subject: "Computer Science",
    role: "Final year",
    trait: "Placement prep",
  },
  {
    id: "10",
    name: "Mehul Jain",
    interest: "Business & Economics",
    level: "Beginner",
    availability: "Weekdays",
    subject: "Commerce",
    role: "MBA aspirant",
    trait: "Case studies",
  },
  {
    id: "11",
    name: "Priyanka Nair",
    interest: "Quantum Physics",
    level: "Intermediate",
    availability: "Weekdays",
    subject: "Science",
    role: "Research student",
    trait: "Analytical mind",
  },
  {
    id: "12",
    name: "Vikram Rathore",
    interest: "Discrete Mathematics",
    level: "Beginner",
    availability: "Weekends",
    subject: "Mathematics",
    role: "Undergraduate",
    trait: "Detail oriented",
  },
  {
    id: "13",
    name: "Sanya Gupta",
    interest: "React & Next.js",
    level: "Intermediate",
    availability: "Weekdays",
    subject: "Computer Science",
    role: "Freelancer",
    trait: "Quick learner",
  },
  {
    id: "14",
    name: "Arjun Mehta",
    interest: "Microeconomics",
    level: "Advanced",
    availability: "Weekends",
    subject: "Commerce",
    role: "Professional",
    trait: "Goal oriented",
  },
  {
    id: "15",
    name: "Tanya Misra",
    interest: "Database Management",
    level: "Intermediate",
    availability: "Weekdays",
    subject: "Computer Science",
    role: "Junior Developer",
    trait: "Problem solver",
  },
];